GET https://restcountries.com/v3.1/name/Republic of India?fields=flags,cca3,capital,languages,currencies,continents,name,borders,independent,population,area,region,callingCodes,subregion,unMember

//

